# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: altimeter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import time_pb2 as time__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='altimeter.proto',
  package='gazebo.msgs',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x61ltimeter.proto\x12\x0bgazebo.msgs\x1a\ntime.proto\"~\n\tAltimeter\x12\x1f\n\x04time\x18\x01 \x02(\x0b\x32\x11.gazebo.msgs.Time\x12\x19\n\x11vertical_position\x18\x02 \x02(\x01\x12\x19\n\x11vertical_velocity\x18\x03 \x02(\x01\x12\x1a\n\x12vertical_reference\x18\x04 \x02(\x01')
  ,
  dependencies=[time__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ALTIMETER = _descriptor.Descriptor(
  name='Altimeter',
  full_name='gazebo.msgs.Altimeter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='gazebo.msgs.Altimeter.time', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vertical_position', full_name='gazebo.msgs.Altimeter.vertical_position', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vertical_velocity', full_name='gazebo.msgs.Altimeter.vertical_velocity', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vertical_reference', full_name='gazebo.msgs.Altimeter.vertical_reference', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=170,
)

_ALTIMETER.fields_by_name['time'].message_type = time__pb2._TIME
DESCRIPTOR.message_types_by_name['Altimeter'] = _ALTIMETER

Altimeter = _reflection.GeneratedProtocolMessageType('Altimeter', (_message.Message,), dict(
  DESCRIPTOR = _ALTIMETER,
  __module__ = 'altimeter_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.Altimeter)
  ))
_sym_db.RegisterMessage(Altimeter)


# @@protoc_insertion_point(module_scope)
