# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: battery.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='battery.proto',
  package='gazebo.msgs',
  syntax='proto2',
  serialized_pb=_b('\n\rbattery.proto\x12\x0bgazebo.msgs\"(\n\x07\x42\x61ttery\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x07voltage\x18\x02 \x02(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BATTERY = _descriptor.Descriptor(
  name='Battery',
  full_name='gazebo.msgs.Battery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gazebo.msgs.Battery.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage', full_name='gazebo.msgs.Battery.voltage', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['Battery'] = _BATTERY

Battery = _reflection.GeneratedProtocolMessageType('Battery', (_message.Message,), dict(
  DESCRIPTOR = _BATTERY,
  __module__ = 'battery_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.Battery)
  ))
_sym_db.RegisterMessage(Battery)


# @@protoc_insertion_point(module_scope)
