# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera_lens.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='camera_lens.proto',
  package='gazebo.msgs',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x63\x61mera_lens.proto\x12\x0bgazebo.msgs\"\xab\x01\n\nCameraLens\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\n\n\x02\x63\x31\x18\x02 \x01(\x01\x12\n\n\x02\x63\x32\x18\x03 \x01(\x01\x12\n\n\x02\x63\x33\x18\x04 \x01(\x01\x12\t\n\x01\x66\x18\x05 \x01(\x01\x12\x0b\n\x03\x66un\x18\x06 \x01(\t\x12\x15\n\rscale_to_hfov\x18\x07 \x01(\x08\x12\x14\n\x0c\x63utoff_angle\x18\x08 \x01(\x01\x12\x0c\n\x04hfov\x18\t \x01(\x01\x12\x18\n\x10\x65nv_texture_size\x18\n \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CAMERALENS = _descriptor.Descriptor(
  name='CameraLens',
  full_name='gazebo.msgs.CameraLens',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='gazebo.msgs.CameraLens.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='c1', full_name='gazebo.msgs.CameraLens.c1', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='c2', full_name='gazebo.msgs.CameraLens.c2', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='c3', full_name='gazebo.msgs.CameraLens.c3', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f', full_name='gazebo.msgs.CameraLens.f', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fun', full_name='gazebo.msgs.CameraLens.fun', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scale_to_hfov', full_name='gazebo.msgs.CameraLens.scale_to_hfov', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cutoff_angle', full_name='gazebo.msgs.CameraLens.cutoff_angle', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hfov', full_name='gazebo.msgs.CameraLens.hfov', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='env_texture_size', full_name='gazebo.msgs.CameraLens.env_texture_size', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=206,
)

DESCRIPTOR.message_types_by_name['CameraLens'] = _CAMERALENS

CameraLens = _reflection.GeneratedProtocolMessageType('CameraLens', (_message.Message,), dict(
  DESCRIPTOR = _CAMERALENS,
  __module__ = 'camera_lens_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.CameraLens)
  ))
_sym_db.RegisterMessage(CameraLens)


# @@protoc_insertion_point(module_scope)
