# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: density.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='density.proto',
  package='gazebo.msgs',
  syntax='proto2',
  serialized_pb=_b('\n\rdensity.proto\x12\x0bgazebo.msgs\"\x1a\n\x07\x44\x65nsity\x12\x0f\n\x07\x64\x65nsity\x18\x01 \x02(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DENSITY = _descriptor.Descriptor(
  name='Density',
  full_name='gazebo.msgs.Density',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='density', full_name='gazebo.msgs.Density.density', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=56,
)

DESCRIPTOR.message_types_by_name['Density'] = _DENSITY

Density = _reflection.GeneratedProtocolMessageType('Density', (_message.Message,), dict(
  DESCRIPTOR = _DENSITY,
  __module__ = 'density_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.Density)
  ))
_sym_db.RegisterMessage(Density)


# @@protoc_insertion_point(module_scope)
