# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: distortion.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vector2d_pb2 as vector2d__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='distortion.proto',
  package='gazebo.msgs',
  syntax='proto2',
  serialized_pb=_b('\n\x10\x64istortion.proto\x12\x0bgazebo.msgs\x1a\x0evector2d.proto\"o\n\nDistortion\x12%\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x15.gazebo.msgs.Vector2d\x12\n\n\x02k1\x18\x02 \x01(\x01\x12\n\n\x02k2\x18\x03 \x01(\x01\x12\n\n\x02k3\x18\x04 \x01(\x01\x12\n\n\x02p1\x18\x05 \x01(\x01\x12\n\n\x02p2\x18\x06 \x01(\x01')
  ,
  dependencies=[vector2d__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DISTORTION = _descriptor.Descriptor(
  name='Distortion',
  full_name='gazebo.msgs.Distortion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='center', full_name='gazebo.msgs.Distortion.center', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='k1', full_name='gazebo.msgs.Distortion.k1', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='k2', full_name='gazebo.msgs.Distortion.k2', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='k3', full_name='gazebo.msgs.Distortion.k3', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='p1', full_name='gazebo.msgs.Distortion.p1', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='p2', full_name='gazebo.msgs.Distortion.p2', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=160,
)

_DISTORTION.fields_by_name['center'].message_type = vector2d__pb2._VECTOR2D
DESCRIPTOR.message_types_by_name['Distortion'] = _DISTORTION

Distortion = _reflection.GeneratedProtocolMessageType('Distortion', (_message.Message,), dict(
  DESCRIPTOR = _DISTORTION,
  __module__ = 'distortion_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.Distortion)
  ))
_sym_db.RegisterMessage(Distortion)


# @@protoc_insertion_point(module_scope)
