# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fluid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vector3d_pb2 as vector3d__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fluid.proto',
  package='gazebo.msgs',
  syntax='proto2',
  serialized_pb=_b('\n\x0b\x66luid.proto\x12\x0bgazebo.msgs\x1a\x0evector3d.proto\">\n\x05\x46luid\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\'\n\x08position\x18\x02 \x03(\x0b\x32\x15.gazebo.msgs.Vector3d')
  ,
  dependencies=[vector3d__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FLUID = _descriptor.Descriptor(
  name='Fluid',
  full_name='gazebo.msgs.Fluid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gazebo.msgs.Fluid.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='gazebo.msgs.Fluid.position', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=106,
)

_FLUID.fields_by_name['position'].message_type = vector3d__pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['Fluid'] = _FLUID

Fluid = _reflection.GeneratedProtocolMessageType('Fluid', (_message.Message,), dict(
  DESCRIPTOR = _FLUID,
  __module__ = 'fluid_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.Fluid)
  ))
_sym_db.RegisterMessage(Fluid)


# @@protoc_insertion_point(module_scope)
