# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import joint_pb2 as joint__pb2
import link_pb2 as link__pb2
import plugin_pb2 as plugin__pb2
import pose_pb2 as pose__pb2
import visual_pb2 as visual__pb2
import vector3d_pb2 as vector3d__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='model.proto',
  package='gazebo.msgs',
  syntax='proto2',
  serialized_pb=_b('\n\x0bmodel.proto\x12\x0bgazebo.msgs\x1a\x0bjoint.proto\x1a\nlink.proto\x1a\x0cplugin.proto\x1a\npose.proto\x1a\x0cvisual.proto\x1a\x0evector3d.proto\"\xe8\x02\n\x05Model\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x01(\r\x12\x11\n\tis_static\x18\x03 \x01(\x08\x12\x1f\n\x04pose\x18\x04 \x01(\x0b\x32\x11.gazebo.msgs.Pose\x12!\n\x05joint\x18\x05 \x03(\x0b\x32\x12.gazebo.msgs.Joint\x12\x1f\n\x04link\x18\x06 \x03(\x0b\x32\x11.gazebo.msgs.Link\x12\x0f\n\x07\x64\x65leted\x18\x07 \x01(\x08\x12#\n\x06visual\x18\x08 \x03(\x0b\x32\x13.gazebo.msgs.Visual\x12$\n\x05scale\x18\t \x01(\x0b\x32\x15.gazebo.msgs.Vector3d\x12\x14\n\x0cself_collide\x18\n \x01(\x08\x12\x13\n\x0b\x65nable_wind\x18\x0b \x01(\x08\x12!\n\x05model\x18\x0c \x03(\x0b\x32\x12.gazebo.msgs.Model\x12#\n\x06plugin\x18\r \x03(\x0b\x32\x13.gazebo.msgs.Plugin')
  ,
  dependencies=[joint__pb2.DESCRIPTOR,link__pb2.DESCRIPTOR,plugin__pb2.DESCRIPTOR,pose__pb2.DESCRIPTOR,visual__pb2.DESCRIPTOR,vector3d__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='gazebo.msgs.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gazebo.msgs.Model.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='gazebo.msgs.Model.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_static', full_name='gazebo.msgs.Model.is_static', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='gazebo.msgs.Model.pose', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='joint', full_name='gazebo.msgs.Model.joint', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='link', full_name='gazebo.msgs.Model.link', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deleted', full_name='gazebo.msgs.Model.deleted', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='visual', full_name='gazebo.msgs.Model.visual', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scale', full_name='gazebo.msgs.Model.scale', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='self_collide', full_name='gazebo.msgs.Model.self_collide', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable_wind', full_name='gazebo.msgs.Model.enable_wind', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='gazebo.msgs.Model.model', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='plugin', full_name='gazebo.msgs.Model.plugin', index=12,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=470,
)

_MODEL.fields_by_name['pose'].message_type = pose__pb2._POSE
_MODEL.fields_by_name['joint'].message_type = joint__pb2._JOINT
_MODEL.fields_by_name['link'].message_type = link__pb2._LINK
_MODEL.fields_by_name['visual'].message_type = visual__pb2._VISUAL
_MODEL.fields_by_name['scale'].message_type = vector3d__pb2._VECTOR3D
_MODEL.fields_by_name['model'].message_type = _MODEL
_MODEL.fields_by_name['plugin'].message_type = plugin__pb2._PLUGIN
DESCRIPTOR.message_types_by_name['Model'] = _MODEL

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'model_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.Model)
  ))
_sym_db.RegisterMessage(Model)


# @@protoc_insertion_point(module_scope)
