# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: param.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import any_pb2 as any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='param.proto',
  package='gazebo.msgs',
  syntax='proto2',
  serialized_pb=_b('\n\x0bparam.proto\x12\x0bgazebo.msgs\x1a\tany.proto\"\\\n\x05Param\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.gazebo.msgs.Any\x12$\n\x08\x63hildren\x18\x03 \x03(\x0b\x32\x12.gazebo.msgs.Param')
  ,
  dependencies=[any__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PARAM = _descriptor.Descriptor(
  name='Param',
  full_name='gazebo.msgs.Param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gazebo.msgs.Param.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='gazebo.msgs.Param.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='children', full_name='gazebo.msgs.Param.children', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=131,
)

_PARAM.fields_by_name['value'].message_type = any__pb2._ANY
_PARAM.fields_by_name['children'].message_type = _PARAM
DESCRIPTOR.message_types_by_name['Param'] = _PARAM

Param = _reflection.GeneratedProtocolMessageType('Param', (_message.Message,), dict(
  DESCRIPTOR = _PARAM,
  __module__ = 'param_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.Param)
  ))
_sym_db.RegisterMessage(Param)


# @@protoc_insertion_point(module_scope)
