# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: param_v.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import param_pb2 as param__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='param_v.proto',
  package='gazebo.msgs',
  syntax='proto2',
  serialized_pb=_b('\n\rparam_v.proto\x12\x0bgazebo.msgs\x1a\x0bparam.proto\",\n\x07Param_V\x12!\n\x05param\x18\x01 \x03(\x0b\x32\x12.gazebo.msgs.Param')
  ,
  dependencies=[param__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PARAM_V = _descriptor.Descriptor(
  name='Param_V',
  full_name='gazebo.msgs.Param_V',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='param', full_name='gazebo.msgs.Param_V.param', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=87,
)

_PARAM_V.fields_by_name['param'].message_type = param__pb2._PARAM
DESCRIPTOR.message_types_by_name['Param_V'] = _PARAM_V

Param_V = _reflection.GeneratedProtocolMessageType('Param_V', (_message.Message,), dict(
  DESCRIPTOR = _PARAM_V,
  __module__ = 'param_v_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.Param_V)
  ))
_sym_db.RegisterMessage(Param_V)


# @@protoc_insertion_point(module_scope)
