# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_cmd_stats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_cmd_pb2 as user__cmd__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='user_cmd_stats.proto',
  package='gazebo.msgs',
  syntax='proto2',
  serialized_pb=_b('\n\x14user_cmd_stats.proto\x12\x0bgazebo.msgs\x1a\x0euser_cmd.proto\"\x8e\x01\n\x0cUserCmdStats\x12\x16\n\x0eundo_cmd_count\x18\x01 \x02(\r\x12\x16\n\x0eredo_cmd_count\x18\x02 \x02(\r\x12&\n\x08undo_cmd\x18\x03 \x03(\x0b\x32\x14.gazebo.msgs.UserCmd\x12&\n\x08redo_cmd\x18\x04 \x03(\x0b\x32\x14.gazebo.msgs.UserCmd')
  ,
  dependencies=[user__cmd__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_USERCMDSTATS = _descriptor.Descriptor(
  name='UserCmdStats',
  full_name='gazebo.msgs.UserCmdStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='undo_cmd_count', full_name='gazebo.msgs.UserCmdStats.undo_cmd_count', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='redo_cmd_count', full_name='gazebo.msgs.UserCmdStats.redo_cmd_count', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='undo_cmd', full_name='gazebo.msgs.UserCmdStats.undo_cmd', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='redo_cmd', full_name='gazebo.msgs.UserCmdStats.redo_cmd', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=196,
)

_USERCMDSTATS.fields_by_name['undo_cmd'].message_type = user__cmd__pb2._USERCMD
_USERCMDSTATS.fields_by_name['redo_cmd'].message_type = user__cmd__pb2._USERCMD
DESCRIPTOR.message_types_by_name['UserCmdStats'] = _USERCMDSTATS

UserCmdStats = _reflection.GeneratedProtocolMessageType('UserCmdStats', (_message.Message,), dict(
  DESCRIPTOR = _USERCMDSTATS,
  __module__ = 'user_cmd_stats_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.UserCmdStats)
  ))
_sym_db.RegisterMessage(UserCmdStats)


# @@protoc_insertion_point(module_scope)
