# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wind.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vector3d_pb2 as vector3d__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wind.proto',
  package='gazebo.msgs',
  syntax='proto2',
  serialized_pb=_b('\n\nwind.proto\x12\x0bgazebo.msgs\x1a\x0evector3d.proto\"K\n\x04Wind\x12.\n\x0flinear_velocity\x18\x01 \x01(\x0b\x32\x15.gazebo.msgs.Vector3d\x12\x13\n\x0b\x65nable_wind\x18\x02 \x01(\x08')
  ,
  dependencies=[vector3d__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WIND = _descriptor.Descriptor(
  name='Wind',
  full_name='gazebo.msgs.Wind',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='linear_velocity', full_name='gazebo.msgs.Wind.linear_velocity', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable_wind', full_name='gazebo.msgs.Wind.enable_wind', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=118,
)

_WIND.fields_by_name['linear_velocity'].message_type = vector3d__pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['Wind'] = _WIND

Wind = _reflection.GeneratedProtocolMessageType('Wind', (_message.Message,), dict(
  DESCRIPTOR = _WIND,
  __module__ = 'wind_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.Wind)
  ))
_sym_db.RegisterMessage(Wind)


# @@protoc_insertion_point(module_scope)
